version: '3.8'

services:
  web-app:
    build: ./
    command: ./app
    ports:
      - 8001:8001
    depends_on:
      - db
    environment:
      - DB_PASSWORD=root
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001"]
      interval: 30s
      timeout: 10s
      retries: 5


  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
      - ./schema/000001_init.up.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - 5436:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  auth-server:
    build: ../auth
    command: ./app
    ports:
      - 8002:8002
    depends_on:
      - db
    environment:
      - DB_PASSWORD=root
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  react-app:
    build: ../front
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production